"""Baseline: create all tables from current metadata (idempotent).

This baseline intentionally uses metadata.create_all with checkfirst=True so
it is safe to run against BOTH a fresh database AND the existing production
database that was previously managed by Base.metadata.create_all. Missing
columns on pre-existing tables are added by the additive sync below.

Future schema changes must be normal autogenerated revisions:
    alembic revision --autogenerate -m "describe change"

Revision ID: 0001_baseline
Revises:
Create Date: 2026-07-06
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect, text

revision = "0001_baseline"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    from app.database import Base
    from app import models  # noqa: F401 — registers all tables

    bind = op.get_bind()
    Base.metadata.create_all(bind=bind, checkfirst=True)

    # Additive column sync for tables that pre-date this baseline
    inspector = inspect(bind)
    for table in Base.metadata.sorted_tables:
        existing_cols = {c["name"] for c in inspector.get_columns(table.name)}
        for column in table.columns:
            if column.name in existing_cols:
                continue
            col_type = column.type.compile(bind.dialect)
            ddl = f'ALTER TABLE {table.name} ADD COLUMN "{column.name}" {col_type}'
            default = getattr(column.default, "arg", None)
            if isinstance(default, bool):
                ddl += f" DEFAULT {'TRUE' if default else 'FALSE'}"
            elif isinstance(default, (int, float)):
                ddl += f" DEFAULT {default}"
            elif isinstance(default, str):
                ddl += f" DEFAULT '{default}'"
            bind.execute(text(ddl))


def downgrade() -> None:
    # Baseline is not reversible: it may have adopted pre-existing tables.
    raise NotImplementedError("Cannot downgrade past the baseline revision.")
